apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-stress
  template:
    metadata:
      labels:
        app: nginx-stress
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
