apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: default
spec:
  containers:
  - name: debug-container
    image: nicolaka/netshoot:latest
    command:
    - sleep
    - "infinity"
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    stdin: true
    tty: true
