# ScaledObject for service1 (memory-intensive)
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: memory-service-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: memory-intensive
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prediction-service.default.svc.cluster.local:5000
        metricName: service1_cpu_usage_prediction
        query: service1_predicted_cpu_usage
        threshold: "75"
    - type: prometheus
      metadata:
        serverAddress: http://prediction-service.default.svc.cluster.local:5000
        metricName: service1_memory_usage_prediction
        query: service1_predicted_memory_usage
        threshold: "500"
---
# ScaledObject for service2 (cpu-intensive)
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-service-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-intensive
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prediction-service.default.svc.cluster.local:5000
        metricName: service2_cpu_usage_prediction
        query: service2_predicted_cpu_usage
        threshold: "75"
    - type: prometheus
      metadata:
        serverAddress: http://prediction-service.default.svc.cluster.local:5000
        metricName: service2_memory_usage_prediction
        query: service2_predicted_memory_usage
        threshold: "500"
